server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: '*'


db:
  url: jdbc:postgresql://localhost:5433/postgres
  username: postgres
  driver-class-name: org.postgresql.Driver
  schema: public

