server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  config: classpath:logback.xml

info:
  version: 1

db:
  url: jdbc:postgresql://localhost:5433/postgres
  username: postgres
  driver-class-name: org.postgresql.Driver
  schema: public

