CREATE TABLE product
(
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY ,
  brand               VARCHAR (100) NOT NULL,
  name                VARCHAR (20) NOT NULL,
  price               BIGINT,
  quantity            INT NOT NULL,
  is_deleted          BOOLEAN NOT NULL
);

create sequence product_tab_sequence start with 1 increment by 1;